//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pscx.Deprecated.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pscx.Deprecated.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} PSCX cmdlet has been deprecated.  Change your script to use {1}..
        /// </summary>
        internal static string DeprecatedCmdlet_F2 {
            get {
                return ResourceManager.GetString("DeprecatedCmdlet_F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:&apos;{0}&apos;, Args:&apos;{1}&apos;, WorkingDir:&apos;{2}&apos;.
        /// </summary>
        internal static string ShouldProcessStartProcess_F3 {
            get {
                return ResourceManager.GetString("ShouldProcessStartProcess_F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the Process object: The remote process id {0} has already exited..
        /// </summary>
        internal static string StartProcessExitedTooSoon {
            get {
                return ResourceManager.GetString("StartProcessExitedTooSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start process {0} on {1}..
        /// </summary>
        internal static string StartProcessFailed {
            get {
                return ResourceManager.GetString("StartProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have specified environment for a remote process. Please make sure that ALL variables, which the remote process (or his children) may use, are set correctly. Everything you leave default will be copied from local environment (including SystemRoot, ProgramFiles and others)!.
        /// </summary>
        internal static string StartProcessRemoteEnvironment {
            get {
                return ResourceManager.GetString("StartProcessRemoteEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} timed out waiting for process id {1} to exit..
        /// </summary>
        internal static string StartProcessTimeout {
            get {
                return ResourceManager.GetString("StartProcessTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping {0}.  It is already unblocked..
        /// </summary>
        internal static string UnblockedAlready_F1 {
            get {
                return ResourceManager.GetString("UnblockedAlready_F1", resourceCulture);
            }
        }
    }
}
