//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pscx.Win.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pscx.Win.Properties.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building the downloaded assemblies cache index..
        /// </summary>
        internal static string AssemblyCacheDownloadLoading {
            get {
                return ResourceManager.GetString("AssemblyCacheDownloadLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Assembly Cache.
        /// </summary>
        internal static string AssemblyCacheGacDriveDescription {
            get {
                return ResourceManager.GetString("AssemblyCacheGacDriveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building the global assembly cache index..
        /// </summary>
        internal static string AssemblyCacheGacLoading {
            get {
                return ResourceManager.GetString("AssemblyCacheGacLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will attempt to load every assembly in the GAC. Are you sure you want to do this?.
        /// </summary>
        internal static string AssemblyCacheLoadEntireGac {
            get {
                return ResourceManager.GetString("AssemblyCacheLoadEntireGac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building the NGen cache index..
        /// </summary>
        internal static string AssemblyCacheNGenLoading {
            get {
                return ResourceManager.GetString("AssemblyCacheNGenLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retreieve the canonical name of the object &apos;{0}&apos;..
        /// </summary>
        internal static string CannotGetDirectoryEntryCanonicalName {
            get {
                return ResourceManager.GetString("CannotGetDirectoryEntryCanonicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve hostname &apos;{0}&apos;..
        /// </summary>
        internal static string HostNameResolveFailed {
            get {
                return ResourceManager.GetString("HostNameResolveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected pipeline object of type {0}, got {1}..
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid IP address..
        /// </summary>
        internal static string InvalidIPAddress {
            get {
                return ResourceManager.GetString("InvalidIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type {0}.
        /// </summary>
        internal static string ObjectMustBeOfType {
            get {
                return ResourceManager.GetString("ObjectMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to &apos;{0}&apos; was denied..
        /// </summary>
        internal static string UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown encoding &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownEncoding {
            get {
                return ResourceManager.GetString("UnknownEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Windows 7 or later required..
        /// </summary>
        internal static string Windows7Required {
            get {
                return ResourceManager.GetString("Windows7Required", resourceCulture);
            }
        }
    }
}
