//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pscx.Resources {
        
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pscx.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was canceled by the user..
        /// </summary>
        internal static string CanceledByUser {
            get {
                return ResourceManager.GetString("CanceledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add values to the {0} property..
        /// </summary>
        internal static string CannotAddItemProperty {
            get {
                return ResourceManager.GetString("CannotAddItemProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retreieve the canonical name of the object &apos;{0}&apos;..
        /// </summary>
        internal static string CannotGetDirectoryEntryCanonicalName {
            get {
                return ResourceManager.GetString("CannotGetDirectoryEntryCanonicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not remove values from the {0} property..
        /// </summary>
        internal static string CannotRemoveItemProperty {
            get {
                return ResourceManager.GetString("CannotRemoveItemProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The drive root cannot be renamed..
        /// </summary>
        internal static string CannotRenameRoot {
            get {
                return ResourceManager.GetString("CannotRenameRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not set the value of the {0} property..
        /// </summary>
        internal static string CannotSetItemProperty {
            get {
                return ResourceManager.GetString("CannotSetItemProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; is not empty..
        /// </summary>
        internal static string DirectoryNotEmpty {
            get {
                return ResourceManager.GetString("DirectoryNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the directory &apos;{0}&apos;..
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the file &apos;{0}&apos;..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve hostname &apos;{0}&apos;..
        /// </summary>
        internal static string HostNameResolveFailed {
            get {
                return ResourceManager.GetString("HostNameResolveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are illegal characters in path &apos;{0}&apos;.
        /// </summary>
        internal static string IllegalCharsInPath {
            get {
                return ResourceManager.GetString("IllegalCharsInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters {0} and {1} are incompatible. {2}.
        /// </summary>
        internal static string IncompatibleArrayParameters {
            get {
                return ResourceManager.GetString("IncompatibleArrayParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoding argument &apos;{1}&apos; for the parameter {0} is not valid.  Valid values are {2}..
        /// </summary>
        internal static string InvalidFileEncodingArgument {
            get {
                return ResourceManager.GetString("InvalidFileEncodingArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected pipeline object of type {0}, got {1}..
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid IP address..
        /// </summary>
        internal static string InvalidIPAddress {
            get {
                return ResourceManager.GetString("InvalidIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item &apos;{0}&apos; is not a reparse point..
        /// </summary>
        internal static string IsNotReparsePoint {
            get {
                return ResourceManager.GetString("IsNotReparsePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither the -{0} parameter was specified nor was the ${1} variable set..
        /// </summary>
        internal static string NeitherParameterNorPreferenceSpecified {
            get {
                return ResourceManager.GetString("NeitherParameterNorPreferenceSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type {0}.
        /// </summary>
        internal static string ObjectMustBeOfType {
            get {
                return ResourceManager.GetString("ObjectMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} resolving path &apos;{1}&apos; resulted in zero resolved paths.  If the path specifies a single file or directory path that happens to contain wildcard characters then use the -LiteralPath parameter or equivalent..
        /// </summary>
        internal static string PathCouldNotBeResolved_F2 {
            get {
                return ResourceManager.GetString("PathCouldNotBeResolved_F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible type specified for preference variable {0}.  Expected {1}, got {2}.
        /// </summary>
        internal static string PreferenceVariableIncompatibleType {
            get {
                return ResourceManager.GetString("PreferenceVariableIncompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already is a different context provider set on this thread..
        /// </summary>
        internal static string ProviderContextAlreadySet {
            get {
                return ResourceManager.GetString("ProviderContextAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task is already added to a task manager..
        /// </summary>
        internal static string TaskAlreadyAddedToAManager {
            get {
                return ResourceManager.GetString("TaskAlreadyAddedToAManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to &apos;{0}&apos; was denied..
        /// </summary>
        internal static string UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown encoding &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownEncoding {
            get {
                return ResourceManager.GetString("UnknownEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown non-SI unit &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownNonSIUnit {
            get {
                return ResourceManager.GetString("UnknownNonSIUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Windows 7 or later required..
        /// </summary>
        internal static string Windows7Required {
            get {
                return ResourceManager.GetString("Windows7Required", resourceCulture);
            }
        }
    }
}
